---
galaxy_info:
  author: Rome
  description: Ansible Galaxy role for installing Tomcat 8
  license: MIT
  min_ansible_version: 2.0
  max_ansible_version: 2.3
  platforms:
  - name: Ubuntu
    versions:
    - xenial
  - name: EL
    versions:
      - 7
  galaxy_tags:
    - tomcat
    - rome
    - CLAW
    - servlet
    - container
    - installer
    - web
